import { translation } from "./zh-CN";

export const en_US: translation = {
    Iam: 'English',
    Message: {
        unsupportImage: 'Image format is not supported',
        sameFilename: 'File name conflicts, using the old file',
        contentFileNotFound: 'Core/Data File not found',
        imageLoadFailButLink: 'Failed to load image, using as link',
        directoryNotSupported: 'Directory not supported for now',
        imageOrLinkNotRecognized: 'Image or link not recognized',
        copy2clipboard: 'Copied to clipboard',
        fail2share: 'Share link failed to generate',
        fail2export: 'Failed to export',
        fail2import: 'Failed to import',
        unsupportFile: 'Unsupported file format',
        imageLoadFail_UseLinkInstead: 'Failed to load image, using online link now',
        invalidLink: 'Invalid link',
        file: 'File',
        loadFails_reasonIs: 'Failed to load, the reason is',
        GFMSupported: 'GFM supported',
        NoFileUploaded_NoNodeSelected: 'No File uploaded or no Node selected',
        NoNodeSelected: 'No Node selected',
        'FileDeleteConfirm?': 'Are you sure to delete this file?',
        CanNotUndone: 'Cannot be undone',
    },
    Operation: {
        share: 'Share',
        export: 'Export',
        import: 'Import',
        redo: 'Redo',
        undo: 'Undo',
        search: 'Search',
        appendParent: '+Parent Node',
        appendSibling: '+Sibling Node',
        appendChild: '+Child Node',
        arrangeUp: 'Arrange Up',
        arrangeDown: 'Arrange Down',
        edit: 'Edit',
        text: 'Text',
        delete: 'Delete',
        link: 'Link',
        linkHint: 'paste link',
        image: 'Image',
        imageHint: `paste image's link`,
        imageUploadHint: 'dblclick to upload image',
        note: 'Note',
        extra: 'File',
        priority: 'Priority',
        progress: 'Progress',
        reset: 'reset',
        tag: 'Tag',
        remove: 'Remove',
        back: 'Back',
    },
    MainDrawer: {
        tag: 'Tag',
        allResources: 'All Resources',
    },
    MultiSelect: {
        all: 'All',
        revert: 'Revert',
        siblings: 'Siblings',
        level: 'Level',
        path: 'Path',
        tree: 'Tree',
    },
    Statusbar: {
        preview: 'Preview',
        copied: 'Image copied to Clipboard',
        permission: 'Please grant the clipboard access in your browser settings',
        template: 'Template',
        theme: 'Theme',
        resetLayout: 'Reset node\'s layout, default all',
        selectOrDrag: 'Select / Drag',
        center: 'Center',
        editable: 'Editable',
        shortcut: 'Shortcut',
        language: 'Language',
        selection: 'Selected',
        unknown: 'Unknown',
        node: 'node(s)',
        expand: 'Expand',
        select: 'Select',
        focus: 'GotFocus',
        blur: 'LostFocus',
    },
    Shortcuts: {
        'Enter': '+SiblingNode',
        'Tab,Insert': '+ChildNode',
        'Shift+Tab': '+ParentNode',
        'Delete': 'Delete node',
        'Up,Down,Left,Right': 'Navigation',
        'Alt+Up,Down': 'Arrange up/down',
        '/,、': 'Expand/Collpose',
        'Alt+1,2,3,4,5': 'Expand to level N',
        'Alt+`': 'Expand all',
        'E': 'Edit',
        'Ctrl+A': 'Select All',
        'Ctrl+C': 'Copy',
        'Ctrl+X': 'Cut',
        'Ctrl+V': 'Paste',
        'Ctrl+B': 'Bold',
        'Ctrl+I': 'Italic',
        'Ctrl+F': 'Search',
        'Alt+LeftMouse,RightMouse': 'Drag view',
        'MouseWheel,TouchPad': 'Move view',
        'dblclick blank': 'center',
        'Ctrl++,-,MouseWheel': 'Zoom',
        'Ctrl+Shift+L': 'Reset layout',
        'Ctrl+Z': 'Undo',
        'Ctrl+Y': 'Redo',
    },
}