name: gh-pages
on:
  push:
    branches:
      - "alpha"
env:
  PAGES_BRANCH: gh-pages
jobs:
  publish-2-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: install & build
        run: |
          npm ci
          npm run build
      - name: publish
        working-directory: ./dist
        run: |
          git init
          git checkout -b $PAGES_BRANCH
          git add -A
          git -c user.name='${{github.repository.owner}}' -c user.email='${{github.repository.owner}}@outlook.com' commit -m '$GITHUB_RUN_ID $GITHUB_SHA'
          git remote add origin https://${{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git
          git push origin $PAGES_BRANCH -f -q
